name: Daily News Crawl

on:
  schedule:
    - cron: "0 20 * * *"   # 20:00 UTC = 05:00 JST
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  crawl:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: pip-${{ runner.os }}-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run crawler
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LOOKBACK_HOURS: "120"
          OUT_DIR: "out"
          OPENAI_MODEL: "gpt-5-mini"
        run: |
          python news_crawler.py
          ls -la out || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: news-output
          path: out/*
          if-no-files-found: warn
          retention-days: 7

      - name: Send email via Gmail (SMTP)
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_TO: ${{ secrets.GMAIL_TO }}
          GMAIL_SUBJECT_PREFIX: "[News]"
          OUT_DIR: "out"
          LOOKBACK_HOURS: "120"
        run: |
          python send_email.py
